### ISSUE TITLE
部分歌曲无法下载

### ISSUE THREAD

**Issue by dawnlyn** [flben233/OsuToMalodyServer#2]
没想到我居然有朝一日也成了贡献者~ (*/ω＼*)

1：
在遇到Url中有" & "这样的文本时，会导致分割URL参数出错，导致数组越界...

例如：
```
歌曲名：September (yomoha remix)
作者：Earth, Wind & Fire
```

临时解决方案如下：
``` java
    public static Map<String, String> getParams(String url) {
        if (url == null) {
            return null;
        }
        HashMap<String, String> map = new HashMap<>();
        String decode = URLDecoder.decode(url, StandardCharsets.UTF_8);
        // 修改1
        decode = decode.replace(" & ","_VIOLET_");
        String[] split = decode.split("&");
        for (int i = 0; i < split.length; i++) {
            // 修改2
            split[i] = split[i].replace("_VIOLET_"," & ");
            String[] split1;
            if (i == 0) {
                String substring = split[i].substring(split[i].indexOf("?") + 1);
                split1 = substring.split("=");
            } else {
                split1 = split[i].split("=");
            }
            map.put(split1[0], split1[1]);
        }
        return map;
    }
```
位于`UrlUtil.java`中

2：封面加载缓慢，是不是可以考虑先缓存然后使用缓存后的文件发给MalodyV...(我硬盘巨大，丝毫不慌)

PS:本人目前并非专业JAVA开发者

**Comment by dawnlyn** [comment]
不知道为啥，1761682需要m=0的时候才能搜索到...

**Comment by dawnlyn** [comment]
下载太多的时候会有请求过多的错误，会返回一个HTML页面....

**Comment by dawnlyn** [comment]
并且翻页操作不会继续加载歌曲...

**Comment by flben233** [comment]
感谢对本项目的支持~，emm...问题有点多我一个一个来回答吧
1、URL参数提取确实有点偷懒了，应该用正则匹配的，我的锅(
2、封面和歌曲缓存确实有打算弄，但是因为最近事情太多 (比如期末考和各种奇奇怪怪的比赛) 这个项目暂时搁置了，处在一个不上不下的状态
3、1761682这首歌我在官网搜了下只有原版osu的谱面，然而这个工具目前被限制在只能搜到有osu!mania的曲子
4、下载太多估计是osu官网限制，之前因为osu官方的api文档有些乱所以没怎么看，后面看看osu有没有官方的api来提供下载服务或者考虑接入某些镜像站之类的，另外这个问题后续加了缓存之后应该可以有所缓解，再不济就限制请求次数，超过次数的就在队列里等待(
5、首页翻页确实是不会加载歌曲的，因为根本就没写hhh，但是搜索页的翻页是正常的
6、话说这个项目是不是有谁宣传了一下，最近多了很多关注这个项目的人，作为开发者还是得说一句现在还是个半成品的状态，4月中旬之后有空了应该会完善一下

**Comment by dawnlyn** [comment]
好耶~追更，期待后续
